### PR TITLE
Spanish Traslation

### PR DESCRIPTION
**Pull request by SnakeOverflow**
Added Spanish translation

### CODE REVIEW

**Comment by SnakeOverflow** [comment]
I don't know if copying the images files for metadata was necessary but did it just in case.

Any feedback is appreciated.

**Comment by jerameel** [comment]
You can exclude the images for now

we might need a efficient process to auto generate screenshots for multiple translations.

**Comment by SnakeOverflow** [comment]
Is there anything missing for my PR to be added? I just have to  sync and update the index.ts right?

**Comment by jerameel** [comment]
This is all good, thanks!

**Pull request merged**
