### PR TITLE
UI Improvment by Group Transactions by Date

### PR DESCRIPTION
**Pull request by 5mutawa**
A small usability improvement for the transactions screen.

image

### CODE REVIEW

**Comment by jerameel** [comment]
This looks good, I'll probably apply this to recent transactions as well!

**Comment by jerameel** [comment]
Thanks! @5mutawa

**Comment by 5mutawa** [comment]
> This looks good, I'll probably apply this to recent transactions as well!

I did that as well, I will pull request it later. 

I was thinking if changing the recent transactions to be the last three days. What do you think?

**Comment by jerameel** [comment]
Actually did those earlier!

**Pull request merged**
