### PR TITLE
Added italian translation files

### PR DESCRIPTION
**Pull request by Philosobrown**
Added initial italian translation files, waiting for contest clarification to complete the translation.

### CODE REVIEW

**Comment by Philosobrown** [comment]
`  CREDIT: 'Credit',
  DEBIT: 'Debit',`
Is "credit" used as in available amount and debit used as in amount used?

**Comment by jerameel** [comment]
> ` CREDIT: 'Credit', DEBIT: 'Debit',` Is "credit" used as in available amount and debit used as in amount used? @jerameel

Debit is amount flowing IN (income) the account, Credit is OUT (expenses)

**Comment by jerameel** [comment]
@Philosobrown this looks good btw. 

I can merge this already if there's no more adjustments needed.

**Comment by Philosobrown** [comment]
Updated all the new strings in it-IT.ts and added the imports/exports for the italian translation in src\constants\translations.

Let me know if any other file needs to be edited!

**Comment by jerameel** [comment]
Well done, thanks @Philosobrown

**Pull request merged**
